
import './globals.css';
import Navbar from '@/components/navbar';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
    
          <Navbar/>

        </header>
        <main>{children}</main>
        <footer className="w-full h-24 flex items-center justify-center border-t bg-gray-100 py-15">
        <p className="text-gray-600">&copy; 2024 Ebola Information Center</p>
       </footer>
      </body>
    </html>
  );
}
